services:
  api:
    build:
      context: .
      target: api
    container_name: ctm-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - API_PORT=3001
      - DATABASE_URL=file:/app/data/dev.db
      - TZ=America/Mexico_City
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  web:
    build:
      context: .
      target: web
    container_name: ctm-web
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy


